version: '3.9'

services:
  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    container_name: 'nginx'
    links:
      - symfony
  symfony:
    #image: php:8-fpm
    container_name: 'symfony-php'
    build: './docker/php-fpm'
    volumes:
      - ./:/var/www/html

  database:
        image: mariadb:10.4.20
        container_name: 'database'
        environment:
            MYSQL_ROOT_PASSWORD: 'Sup3rS3cr3tPa55'
            MYSQL_DATABASE: dockerized_db
            MYSQL_USER: 'symfony_user'
            MYSQL_PASSWORD: '!ChangeMe!'
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - 3306
        healthcheck:
            test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
            interval: 5s
            retries: 5
        volumes:
          - db_data:/var/lib/mysql
          #- ./docker/db/mariadb/my.cnf:/etc/mysql/conf.d/my.cnf
  database_admin:
        image: phpmyadmin/phpmyadmin:5
        container_name: 'phpMyAdmin'
        ports:
            - '3307:80'
        environment:
            PMA_HOST: database
        depends_on:
            database:
               condition: service_healthy
        volumes:
        - db_admin_data:/var/www/html
volumes:
  db_data:
  db_admin_data:
